version: '3.9'

services:
  db:
    image: postgres:16-alpine
    container_name: micro-tales-db
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: .env
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: microtales
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  db-init:
    build:
      context: .
      dockerfile: db-init.Dockerfile
    env_file: .env
    depends_on:
      db:
        condition: service_healthy


  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DATABASE_URL: postgres://postgres:password@db:5432/microtales
        AUTH_SECRET: random_secret_key
        NEXTAUTH_URL: http://localhost:3000
        HOSTNAME: 0.0.0.0
    container_name: micro-tales-app-dev
    restart: unless-stopped
    ports:
      - '3000:3000'
    env_file: .env
    depends_on:
      db:
        condition: service_healthy

  pgadmin:
    image: dpage/pgadmin4
    container_name: micro-tales-pgadmin
    restart: unless-stopped
    env_file: .env
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@microtales.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "5050:80"
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
